Feature/19 settings: added user configuration setting for time interval
alchemy-be-human/beHuman pull request #7
Opened 2021-01-15 23:09 UTC by RhoneLachner

2021-01-15 23:22 UTC, jillianlg commented on extension.js
> +	//THIS IS WHERE STOP WATCH FUNCTION BEGINS
A reminder that line 56 - 67 needs to be on a new branch with a corresponding ticket for each ie: "feature/#-commands" or "feature/#-resetTime", etc. however the teams decide to break up those tickets. ;)

2021-01-15 23:23 UTC, jillianlg commented on package.json
> +        "command": "be-human.resetTime",
Same deal with line 26 - 38. New branch and ticket!

2021-01-15 23:27 UTC, jillianlg commented
Could we get the command code moved to a new branch before we push this? 
Similar to how I moved the timeInterval code off of the publish branch to the settings branch.

2021-01-15 23:29 UTC, jillianlg requested changes
Could we get the command code moved to a new branch before we push this to dev?
Similar to how I moved the timeInterval code off of the publish branch to the settings branch. :)

We should avoid pushing any "in progress" code to the dev branch.

2021-01-15 23:52 UTC, bryanakitchen approved these changes
Good stuff!

2021-01-16 00:02 UTC, jillianlg approved these changes

2021-01-16 00:02 UTC, jillianlg commented
Thank you!!!! APPROVED. :)

2021-01-16 00:03 UTC, merged